"""Initialize

Revision ID: 589c37a2e37e
Revises: 
Create Date: 2024-09-14 19:17:09.085565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '589c37a2e37e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Drop foreign key constraints first, then drop indexes and tables
    with op.batch_alter_table('expense_has_category', schema=None) as batch_op:
        # Drop foreign key constraints
        batch_op.drop_constraint('fk_expense_has_category_category1', type_='foreignkey')
        batch_op.drop_constraint('fk_expense_has_category_expense1', type_='foreignkey')
        # Now it's safe to drop the indexes
        batch_op.drop_index('fk_expense_has_category_category1_idx')
        batch_op.drop_index('fk_expense_has_category_expense1_idx')

    # Drop the expense_has_category table after dropping constraints and indexes
    op.drop_table('expense_has_category')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        # Drop foreign key constraints first
        batch_op.drop_constraint('fk_expense_user1', type_='foreignkey')
        # Now it's safe to drop the index
        batch_op.drop_index('fk_expense_user1_idx')

    # Drop the expense table
    op.drop_table('expense')

    with op.batch_alter_table('budget_has_category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_budget_has_category_budget1', type_='foreignkey')
        batch_op.drop_constraint('fk_budget_has_category_category1', type_='foreignkey')
        batch_op.drop_index('fk_budget_has_category_budget1_idx')
        batch_op.drop_index('fk_budget_has_category_category1_idx')

    op.drop_table('budget_has_category')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint('fk_budget_user1', type_='foreignkey')
        batch_op.drop_index('fk_budget_user1_idx')

    op.drop_table('budget')

    with op.batch_alter_table('income_has_category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_income_has_category_income', type_='foreignkey')
        batch_op.drop_constraint('fk_income_has_category_category1', type_='foreignkey')
        batch_op.drop_index('fk_income_has_category_income_idx')
        batch_op.drop_index('fk_income_has_category_category1_idx')

    op.drop_table('income_has_category')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_constraint('fk_income_user1', type_='foreignkey')
        batch_op.drop_index('fk_income_user1_idx')

    op.drop_table('income')
    
    op.drop_table('user')
    op.drop_table('category')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_updated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('category',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('filter', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('expense',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_expense_user1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('expense_has_category',
    sa.Column('expense_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_expense_has_category_category1'),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name='fk_expense_has_category_expense1'),
    sa.PrimaryKeyConstraint('expense_id', 'category_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('income',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_income_user1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('income_has_category',
    sa.Column('income_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_income_has_category_category1'),
    sa.ForeignKeyConstraint(['income_id'], ['income.id'], name='fk_income_has_category_income'),
    sa.PrimaryKeyConstraint('income_id', 'category_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('budget',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_budget_user1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('budget_has_category',
    sa.Column('budget_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], name='fk_budget_has_category_budget1'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_budget_has_category_category1'),
    sa.PrimaryKeyConstraint('budget_id', 'category_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
